# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'criarpost.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(910, 668)
        Dialog.setMinimumSize(QtCore.QSize(778, 657))
        Dialog.setMaximumSize(QtCore.QSize(1500, 1000))
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label.setStyleSheet("font: 15pt \"Consolas\";\n"
"color: #00ff00;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_user_post = QtWidgets.QLabel(self.frame)
        self.label_user_post.setStyleSheet("font: 15pt \"Consolas\";\n"
"text-decoration: underline;\n"
"color: #00ff00;")
        self.label_user_post.setObjectName("label_user_post")
        self.horizontalLayout.addWidget(self.label_user_post)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setStyleSheet("font: 10pt \"Consolas\";\n"
"color: #00ff00;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.box_categoria = QtWidgets.QComboBox(self.frame)
        self.box_categoria.setMinimumSize(QtCore.QSize(150, 0))
        self.box_categoria.setMaximumSize(QtCore.QSize(150, 16777215))
        self.box_categoria.setStyleSheet("color: rgb(0, 255, 0);\n"
"font: 10pt \"Consolas\";\n"
"border: 1px solid #00ff00;")
        self.box_categoria.setObjectName("box_categoria")
        self.horizontalLayout.addWidget(self.box_categoria)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_titulo_post = QtWidgets.QLineEdit(self.frame_2)
        self.line_titulo_post.setStyleSheet("border: 1px solid #00ff00;\n"
"font: 10pt \"Consolas\";\n"
"color: #00ff00;")
        self.line_titulo_post.setText("")
        self.line_titulo_post.setObjectName("line_titulo_post")
        self.horizontalLayout_2.addWidget(self.line_titulo_post)
        self.verticalLayout.addWidget(self.frame_2)
        self.text_post_box = QtWidgets.QTextEdit(Dialog)
        self.text_post_box.setStyleSheet("border: 1px solid #00ff00;\n"
"color: #00ff00;\n"
"font: 11pt \"Consolas\";")
        self.text_post_box.setObjectName("text_post_box")
        self.verticalLayout.addWidget(self.text_post_box)
        self.butt_criar_post = QtWidgets.QPushButton(Dialog)
        self.butt_criar_post.setStyleSheet("QPushButton {\n"
"    color: #00ff00;\n"
"    font: 75 13pt \"Consolas\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"      background-color: #003300;\n"
"}")
        self.butt_criar_post.setObjectName("butt_criar_post")
        self.verticalLayout.addWidget(self.butt_criar_post)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "--Escreva seu post--"))
        self.label.setText(_translate("Dialog", "User:"))
        self.label_user_post.setText(_translate("Dialog", "\"Luca Maia Lamonato\""))
        self.label_2.setText(_translate("Dialog", "Categoria:"))
        self.line_titulo_post.setPlaceholderText(_translate("Dialog", "Insira o titulo do Post"))
        self.butt_criar_post.setText(_translate("Dialog", "<CRIAR POST>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
