# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'post.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(936, 754)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(700, 300))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -234, 899, 968))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_text_post = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_text_post.sizePolicy().hasHeightForWidth())
        self.frame_text_post.setSizePolicy(sizePolicy)
        self.frame_text_post.setMinimumSize(QtCore.QSize(200, 100))
        self.frame_text_post.setMaximumSize(QtCore.QSize(16777215, 16000))
        self.frame_text_post.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_text_post.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_text_post.setObjectName("frame_text_post")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_text_post)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.post_butt_coment = QtWidgets.QPushButton(self.frame_text_post)
        self.post_butt_coment.setStyleSheet("QPushButton {\n"
"    color: #00ff00;\n"
"    font: 75 15pt \"Consolas\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"      background-color: #003300;\n"
"}")
        self.post_butt_coment.setObjectName("post_butt_coment")
        self.verticalLayout_3.addWidget(self.post_butt_coment)
        self.frame = QtWidgets.QFrame(self.frame_text_post)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_post_icon = QtWidgets.QLabel(self.frame)
        self.label_post_icon.setMaximumSize(QtCore.QSize(30, 30))
        self.label_post_icon.setStyleSheet("border: 1px solid #00ff00;\n"
"color: #00ff00;\n"
"font: 11pt \"Consolas\";")
        self.label_post_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_post_icon.setObjectName("label_post_icon")
        self.horizontalLayout.addWidget(self.label_post_icon)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_post_nmuser = QtWidgets.QLabel(self.frame)
        self.label_post_nmuser.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_post_nmuser.setStyleSheet("color: #00ff00;\n"
"\n"
"font: 11pt \"Consolas\";\n"
"text-decoration: underline;")
        self.label_post_nmuser.setWordWrap(False)
        self.label_post_nmuser.setObjectName("label_post_nmuser")
        self.horizontalLayout.addWidget(self.label_post_nmuser)
        self.verticalLayout_3.addWidget(self.frame)
        self.text_post = QtWidgets.QLabel(self.frame_text_post)
        self.text_post.setStyleSheet("border: 1px solid #000000;\n"
"color: #00ff00;\n"
"font: 12pt \"Consolas\";")
        self.text_post.setWordWrap(True)
        self.text_post.setObjectName("text_post")
        self.verticalLayout_3.addWidget(self.text_post)
        self.verticalLayout_2.addWidget(self.frame_text_post)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 200))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_comen = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_comen.sizePolicy().hasHeightForWidth())
        self.frame_comen.setSizePolicy(sizePolicy)
        self.frame_comen.setMinimumSize(QtCore.QSize(200, 100))
        self.frame_comen.setMaximumSize(QtCore.QSize(16777215, 16000))
        self.frame_comen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_comen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_comen.setObjectName("frame_comen")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_comen)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.frame_comen)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_coment_icon = QtWidgets.QLabel(self.frame_3)
        self.label_coment_icon.setMaximumSize(QtCore.QSize(30, 30))
        self.label_coment_icon.setStyleSheet("border: 1px solid #00ff00;\n"
"color: #00ff00;\n"
"font: 11pt \"Consolas\";")
        self.label_coment_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_coment_icon.setObjectName("label_coment_icon")
        self.horizontalLayout_2.addWidget(self.label_coment_icon)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_coment_nmuser = QtWidgets.QLabel(self.frame_3)
        self.label_coment_nmuser.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_coment_nmuser.setStyleSheet("color: #00ff00;\n"
"\n"
"font: 11pt \"Consolas\";\n"
"text-decoration: underline;")
        self.label_coment_nmuser.setObjectName("label_coment_nmuser")
        self.horizontalLayout_2.addWidget(self.label_coment_nmuser)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.text_coment = QtWidgets.QLabel(self.frame_comen)
        self.text_coment.setStyleSheet("border: 1px solid #000000;\n"
"color: #00ff00;\n"
"font: 12pt \"Consolas\";")
        self.text_coment.setWordWrap(True)
        self.text_coment.setObjectName("text_coment")
        self.verticalLayout_5.addWidget(self.text_coment)
        self.verticalLayout_4.addWidget(self.frame_comen)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Post"))
        self.post_butt_coment.setText(_translate("MainWindow", "<Comentar>"))
        self.label_post_icon.setText(_translate("MainWindow", ":)"))
        self.label_post_nmuser.setText(_translate("MainWindow", "Nome de Usuario"))
        self.text_post.setText(_translate("MainWindow", "Placa-mãe ITX AM4 está difícil de encontrar (e cara)! Continuo em AM4 ou migro pra AM5/Intel?\n"
"Dúvida\n"
"Boa noite, pessoal! Estou montando um PC no gabinete Cooler Master NR200 e já tenho:\n"
"- CPU: Ryzen 7 5700X\n"
"- GPU: RX 580 2048SP\n"
"- 2×16 GB RAM\n"
"- SSD NVMe\n"
"- Gabinete NR200\n"
"\n"
"Os próximos passos seriam comprar uma placa‑mãe ITX, depois fonte SFX e um air‑cooler.\n"
"\n"
"Problema:\n"
"- Difícil encontrar placa‑mãe mini‑ITX AM4 no Brasil.\n"
"- As poucas que aparecem custam a partir de R$ 1300, chegando a R$ 1.500 ou mais, fora do meu orçamento atual (tenho cerca de R$ 1.100).\n"
"\n"
"Opções que pensei:\n"
"- Continuar em AM4 e garimpar uma B550‑I ou X570‑I cara (R$ 1.300+)\n"
"- Partir pra Intel LGA1700 ou AM5, onde parece ter mais oferta de ITX e preços similares, mas abro mão do meu Ryzen 7.\n"
"\n"
"Pergunta:\n"
"O que vocês fariam no meu lugar?\n"
"- Continuariam insistindo em AM4, pagando o “prêmio”?\n"
"- Migrariam para AM5 e Intel LGA1700?\n"
"\n"
"Outro:\n"
"- Podem indicar modelos específicos de placa‑mãe em cada plataforma?\n"
"- E já que vou comprar fonte SFX e air‑cooler, sugestões de: Fonte SFX e air‑cooler compatível com NR200.\n"
"\n"
"Obrigado desde já pela ajuda!!"))
        self.label_coment_icon.setText(_translate("MainWindow", ";-;"))
        self.label_coment_nmuser.setText(_translate("MainWindow", "TextLabel"))
        self.text_coment.setText(_translate("MainWindow", "Já tive a pira de gabinete mini ATX, mas peça aqui é horrível e quando tem é cara. Eu pularia pra am5 logo pq depender de quando vir e ainda pagar preço Premium é muito absurdo pra mim."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
