# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comentario.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(778, 657)
        Dialog.setMinimumSize(QtCore.QSize(778, 657))
        Dialog.setMaximumSize(QtCore.QSize(778, 657))
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_coment_box = QtWidgets.QTextEdit(Dialog)
        self.text_coment_box.setStyleSheet("border: 1px solid #00ff00;\n"
"color: #00ff00;\n"
"font: 11pt \"Consolas\";")
        self.text_coment_box.setObjectName("text_coment_box")
        self.verticalLayout.addWidget(self.text_coment_box)
        self.butt_coment = QtWidgets.QPushButton(Dialog)
        self.butt_coment.setStyleSheet("QPushButton {\n"
"    color: #00ff00;\n"
"    font: 75 13pt \"Consolas\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"      background-color: #003300;\n"
"}")
        self.butt_coment.setObjectName("butt_coment")
        self.verticalLayout.addWidget(self.butt_coment)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "--Escreva seu comentario--"))
        self.butt_coment.setText(_translate("Dialog", "<COMENTAR>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
